name: flutter_physics
description: "A Flutter package providing physics-based animations including customizable spring and gravity simulations that can be used both as physics simulations and animation curves."
version: 0.0.1
homepage: https://github.com/sangddn/flutter_physics
repository: https://github.com/sangddn/flutter_physics
issue_tracker: https://github.com/sangddn/flutter_physics/issues

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
